# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff28069aa48f1dcb353eb09c76f6d29bd18899be4b33d185154fddb801a1bf000eff5a8db8af4ee9125c16f886632a0e3a464e3b0fddc61db3e2dc000eb46bf1

test:
  secret_key_base: ff3b1cfd47be7cd72324191491300e6d9dac87e9c452dcc5fe32ee338845b9d0e9cd65ce214374cf136457588aea707a178692cb9f83b7b979ed82f9fadd1649

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
